# Generated by Django 3.0.3 on 2020-05-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
