# Generated by Django 3.0.3 on 2020-05-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200531_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(choices=[(0, 'article'), (1, 'code'), (2, 'photo')], default=0),
        ),
    ]
